### ISSUE TITLE
run_cellstates.py fail to load genes file

### ISSUE THREAD

**Issue by ismara-unibas** [pgrobecker/cellstates#11]
run_cellstates.py fail to load genes file.
Error:
```
Traceback (most recent call last):
  File "/scicore/home/nimwegen/pachko/sc_mara/cellstates/scripts/run_cellstates.py", line 288, in <mod
ule>
    main()
  File "/scicore/home/nimwegen/pachko/sc_mara/cellstates/scripts/run_cellstates.py", line 108, in main
    genes = np.loadtxt(args.genes, dtype=str, delimiter='\n')
  File "/scicore/home/nimwegen/pachko/miniconda3_sc/envs/sc/lib/python3.9/site-packages/numpy/lib/npyi
o.py", line 1308, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/scicore/home/nimwegen/pachko/miniconda3_sc/envs/sc/lib/python3.9/site-packages/numpy/lib/npyi
o.py", line 1006, in _read
    next_arr = _load_from_filelike(
TypeError: control character 'delimiter' cannot be a newline (`\r` or `\n`).
```

Best,

Mikhail

**Comment by kaushik-roy-physics** [comment]
I am getting the same error. I actually converted the .tsv files for features and barcodes generated by CellRanger to simple .txt files with linebreaks. For the features I even simplified by extracting the column of gene names and removing the feature ID and types. Still I get the same error as mentioned above. Just wondering if a resolution has been reached on this issue?

Best,
Kaushik

**Comment by ismara-unibas** [comment]
The bug is fixed.
